#!/usr/bin/env python3
"""Generate and validate `docs/specs/COVERAGE.md` (ADR-028).

Requirement IDs are permanent. This script never assigns, renumbers, or removes one - it
only reads what the specs declare and reconciles it against the register's recorded
statuses. An ID that disappears from the specs is reported as an error, not quietly
dropped, because a silently vanished requirement is the exact failure ADR-028 exists to
catch.

Usage:
    spec_coverage.py            # validate; non-zero exit on drift
    spec_coverage.py --write    # rewrite COVERAGE.md, preserving recorded statuses
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPECS = REPO / "docs" / "specs"
REGISTER = SPECS / "COVERAGE.md"

#: Specs enrolled in ADR-028 coverage. Curate-as-touched: a spec joins this list when it is
#: next edited. Enrollment is explicit so that partial coverage is visible rather than implied.
ENROLLED = ("00", "01", "04", "04a", "05")

ID_RE = re.compile(r"\[(REQ-[0-9a-z]+-\d{3})\]")
ROW_RE = re.compile(
    r"^\|\s*(REQ-[0-9a-z]+-\d{3})\s*\|\s*(\w+)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|$"
)
STATUSES = {"SPECCED", "IMPLEMENTED", "DEFERRED", "DROPPED"}


def spec_files() -> list[Path]:
    out = []
    for p in sorted(SPECS.glob("*.md")):
        prefix = p.name.split("-")[0]
        if prefix in ENROLLED:
            out.append(p)
    return out


def declared() -> dict[str, tuple[str, int, str]]:
    """id -> (spec filename, line number, requirement text)."""
    found: dict[str, tuple[str, int, str]] = {}
    dupes: list[str] = []
    for p in spec_files():
        for lineno, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
            for m in ID_RE.finditer(line):
                rid = m.group(1)
                if rid in found:
                    dupes.append(f"{rid} at {p.name}:{lineno} and {found[rid][0]}:{found[rid][1]}")
                    continue
                text = line[m.end():].strip()
                found[rid] = (p.name, lineno, text)
    if dupes:
        raise SystemExit("duplicate requirement ids: " + "; ".join(dupes))
    return found


def recorded() -> dict[str, tuple[str, str, str]]:
    """id -> (status, evidence, note). Empty when the register does not exist yet."""
    if not REGISTER.is_file():
        return {}
    out: dict[str, tuple[str, str, str]] = {}
    for line in REGISTER.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.match(line.strip())
        if m and m.group(2) in STATUSES:
            out[m.group(1)] = (m.group(2), m.group(3), m.group(4))
    return out


def render(decl: dict, rec: dict) -> str:
    body = [
        "# Spec Coverage Register",
        "",
        "**Generated by `scripts/spec_coverage.py`. Do not hand-edit the tables** - edit a status",
        "or evidence cell, then re-run with `--write` to reconcile. Requirement ids are permanent",
        "and are never reused, including after a requirement is dropped (ADR-028).",
        "",
        f"**Enrolled specs:** {', '.join(ENROLLED)}. Coverage is partial by design; a spec joins",
        "the enrolled set when it is next edited. Specs not listed carry no ids yet.",
        "",
        "| Status | Meaning | Evidence required |",
        "|---|---|---|",
        "| `SPECCED` | Stated, not yet built | - |",
        "| `IMPLEMENTED` | Built | a `path:line` or test name that resolves |",
        "| `DEFERRED` | Postponed to a named phase | the phase name |",
        "| `DROPPED` | No longer a requirement | an ADR reference |",
        "",
    ]
    by_spec: dict[str, list[str]] = {}
    for rid in sorted(decl):
        by_spec.setdefault(decl[rid][0], []).append(rid)
    for spec in sorted(by_spec):
        body += [f"## {spec}", "", "| id | status | evidence | note |", "|---|---|---|---|"]
        for rid in by_spec[spec]:
            status, evidence, note = rec.get(rid, ("SPECCED", "", ""))
            text = decl[rid][2]
            note = note or (text[:90] + ("..." if len(text) > 90 else ""))
            body.append(f"| {rid} | {status} | {evidence} | {note} |")
        body.append("")

    orphans = sorted(set(rec) - set(decl))
    body += [
        "## Retired ids",
        "",
        "Ids recorded here but no longer present in any spec. An id reaches this table only via a",
        "`DROPPED` status with an ADR reference; anything else appearing here is drift.",
        "",
        "| id | status | evidence | note |",
        "|---|---|---|---|",
    ]
    for rid in orphans:
        s, e, n = rec[rid]
        body.append(f"| {rid} | {s} | {e} | {n} |")
    body.append("")
    counts = {s: 0 for s in STATUSES}
    for rid in decl:
        counts[rec.get(rid, ("SPECCED", "", ""))[0]] += 1
    body += [
        "## Totals",
        "",
        f"{len(decl)} requirements across {len(by_spec)} enrolled specs - "
        + " · ".join(f"{v} {k.lower()}" for k, v in sorted(counts.items()) if v),
        "",
    ]
    return "\n".join(body)


def main() -> int:
    decl = declared()
    rec = recorded()
    write = "--write" in sys.argv

    problems: list[str] = []
    for rid in sorted(set(rec) - set(decl)):
        if rec[rid][0] != "DROPPED":
            problems.append(
                f"{rid} is in the register as {rec[rid][0]} but appears in no spec - "
                "a requirement vanished without being dropped (ADR-028 decision 3)"
            )
    for rid, (status, evidence, _) in sorted(rec.items()):
        if status == "DROPPED" and not re.search(r"ADR-\d{3}", evidence):
            problems.append(f"{rid} is DROPPED without an ADR reference (ADR-028 decision 3)")
        if status == "IMPLEMENTED" and not evidence.strip():
            problems.append(f"{rid} is IMPLEMENTED with no evidence")
        if status == "DEFERRED" and not evidence.strip():
            problems.append(f"{rid} is DEFERRED with no named phase")

    if write:
        REGISTER.write_text(render(decl, rec), encoding="utf-8")
        print(f"wrote {REGISTER.relative_to(REPO)}: {len(decl)} requirements")
    missing = sorted(set(decl) - set(rec))
    if missing and not write:
        problems.append(
            f"{len(missing)} requirement(s) not in the register, first: {missing[0]} "
            "- run scripts/spec_coverage.py --write"
        )
    for p in problems:
        print(f"  {p}")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
